config/routes.rb
Rails.application.routes.draw do
	get 'profiles/show'
	get ':user_name', to: 'profiles#show', as: :profile
	get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
	patch ':user_name/edit', to: 'profiles#update', as: :update_profile
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	resources :posts do
	  resources :comments
	  member do
	  	get 'like', to: "posts#like"
	  	get 'unlike', to: "posts#unlike"
	  end
	end
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base

	acts_as_votable
	belongs_to :user
	validates :user_id, presence: true
	validates :image, presence: true
	validates :legende, length: { minimum: 3, maximum: 500 }

	has_attached_file :image, styles: { :medium => "640x" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	has_many :comments, dependent: :destroy

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  acts_as_voter
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_attached_file :avatar, styles: { medium: '152x152#' }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	#controleur des commentaires
	before_action :set_post
	# méthode creation d'un commenaitre
	def create
		#instance commentaire 
	  @comment = @post.comments.build(comment_params)
	  @comment.user_id = current_user.id
	  	#quand on poste un commentaire on fait appel à un appel ajax pour l'afficher dynamiquement
		if @comment.save
		  respond_to do |format|
		    format.html { redirect_to root_path }
		    format.js
		  end
		else
		  flash[:alert] = "Le commentaire semble avoir un problème..."
		  render root_path
		end
	end

	#méthode supprimer un commentaire
	def destroy

    @comment = @post.comments.find(params[:id])
    #seuls les commentaires appartenant au user connecté au site peuvent supprimer
	    if @comment.user_id == current_user.id
	      @comment.delete
	      respond_to do |format|
	        format.html { redirect_to root_path }
	        format.js
	      end
	    end
	 end

	private

	def comment_params
	  params.require(:comment).permit(:content)
	end

	def set_post
	  @post = Post.find(params[:post_id])
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	 before_action :authenticate_user!
	 before_action :owned_post, only: [:edit, :update, :destroy]
	 before_action :set_post, only: [:show, :edit, :update, :destroy, :like, :unlike]
	

	def index
		#affichage des post dans l'ordre décroissant à leur date de publication
		@posts = Post.all.order('created_at DESC')
	end

	def new
	  @post = current_user.posts.build
	end

	def create
     @post = current_user.posts.build(post_params)

	    if @post.save
	      flash[:success] = "Le post a été crée"
	      redirect_to root_path
	    else
	      flash[:alert] = "Votre post n'a pas été crée, veuillez vérifier le formulaire de post"
	      render :new
	    end
  	end

  	#méthode qui vérifie si le post appartient au user actuel
  	def owned_post
		@post=Post.find(params[:id])
		unless current_user.email == @post.user.email
			flash[:alert] = "Ce post n'est pas à vous" 
			redirect_to root_path
		end
	end

	def show
	end

	def edit
	end

	#méthode qui modifie le post
	def update
	    if @post.update(post_params)
	      flash[:success] = "Post mis à jour"
	      redirect_to root_path
	    else
	      flash.now[:alert] = "Mis à jour impossible, veuillez vérifier vos champs."
	      render :edit
	    end
	end
	
	#méthode qui permet de like un post=> un appel AJAX se fait pour le like, quand on "like"
	# la maj se fait sans rafraichissement de la page
	def like
		if @post.liked_by current_user
	      respond_to do |format|
	        format.html { redirect_to root_path }
	        format.js
	      end
	    end
	end

	#méthode qui retire le like d'un post
	def unlike
		if @post.unliked_by current_user
	      respond_to do |format|
	        format.html { redirect_to root_path }
	        format.js
	      end
	    end
	end

	def destroy
	  @post.destroy
	  redirect_to root_path
	end

	private

	def post_params
	  params.require(:post).permit(:image, :legende)
	end

	def set_post
	    @post = Post.find(params[:id])
	end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	#controle des profiles
	before_action :authenticate_user!
	before_action :owned_profile, only: [:edit, :update]


	def show
		@user = User.find_by(user_name: params[:user_name])
		@posts = User.find_by(user_name: params[:user_name]).posts.order('created_at DESC')
	end

	def edit
	  @user = User.find_by(user_name: params[:user_name])
	end
	#méthode qui met à jour le profil apres modification
	def update
		@user = User.find_by(user_name: params[:user_name])
	    if @user.update(profile_params)
	      flash[:success] = 'Votre profile a été mis à jour'
	      redirect_to profile_path(@user.user_name)
	    else
	      @user.errors.full_messages
	      flash[:error] = @user.errors.full_messages
	      render :edit
	    end
	end
	#méthode qui vérifie si le profil correspond bien à celui qui tente de modifier
	def owned_profile
	    @user = User.find_by(user_name: params[:user_name])
	    unless current_user == @user
	      flash[:alert] = "Hey! ce n'est pas ton profile!"
	      redirect_to root_path
	    end
	end

	private

	def profile_params
	  params.require(:user).permit(:avatar, :bio)
	end

	before_action :set_user
	
	def set_user
	  @user = User.find_by(user_name: params[:user_name])
	 end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	#helper de l'app 


	#on defini le helper qui permet de faire des alerts
	def alert_for(flash_type)
	  { success: 'alert-success',
	    error: 'alert-danger',
	    alert: 'alert-warning',
	    notice: 'alert-info'
	  }[flash_type.to_sym] || flash_type.to_s
	end

	

	def profile_avatar_select(user)
	  return image_tag user.avatar.url(:medium),
	                   id: 'image-preview',
	                   class: 'img-responsive img-circle profile-image' if user.avatar.exists?
	  image_tag 'default-avatar.png', id: 'image-preview',
	                                  class: 'img-responsive img-circle profile-image'
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	#helper post

	#fonction qui affiche les likes s'il y en a moins de 8 on affiche le nombre de like sinon les noms des personnes
	def display_likes(post)
	votes = post.votes_for.up
	return list_likers(votes) if  votes.size <= 8
    		count_likers(votes)
    	end
  	end

  	#fonction qui retourne la class du like selon si le user like ou non le post
  	def liked_post(post)
	return 'glyphicon-heart' if current_user.voted_for? post
		'glyphicon-heart-empty'
	end

	private

	#fonction qui retourne la liste des personnes qui like un post
	def list_likers(votes)
	user_names = []
	unless votes.blank?
		  votes.voters.each do |voter|
		    user_names.push(link_to voter.user_name,
		    profile_path(voter.user_name),
		    class: 'user-name')
		  end
		  user_names.to_sentence.html_safe + like_plural(votes)
		end
	end

	#fonction qui affiche le nombre de likes sur un post
	def count_likers(votes)
	    vote_count = votes.size
	    vote_count.to_s + ' likes'
	end

	#change la phrase selon s'il y a un ou plusieurs qui aime le post
	def like_plural(votes)
	return ' like this' 
		if votes.count > 1
			' likes this'
	end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/comments/_comment.html.erb
<div class="row">
	<span>
		<%=  link_to comment.user.user_name, profile_path(comment.user.user_name) %>
	</span>
	<span class="comment-content">
		<%= comment.content %>
	</span>
</div>
<% if comment.user == current_user %>
	<%= link_to 'Supprimer', post_comment_path(post, comment), method: :delete, remote: true, data: { confirm: "Etes-vous sur?"}%>
<% end %>

app/views/comments/create.js.erb
jQuery('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>");
jQuery('#comment_content_<%= @post.id %>').val('')

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render @post.comments, post: @post, comment: @comment %>");

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse ">
  <div class="container">
  	<div class="navbar-header">
        <%= link_to 'Pictugram', root_path, class: "navbar-brand" %>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
     <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Nouveau post', new_post_path %></li>
          <li><%= link_to 'Déconnexion', destroy_user_session_path, method: :delete %></li>
        <% else %>
      		<li><%= link_to 'Connexion', new_user_session_path %></li>

      		<li><%= link_to 'Inscription', new_user_registration_path %></li>
        <% end %>
    </ul>
  </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictugram</title>
     <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
<% flash.each do |nom, message| %>
	<%= content_tag :div, message, class: [:alert, alert_for(nom)] %>
	<% end %>
    <%= yield %>

  </body>
</html>

app/views/posts/_likes.html.erb
<div id= "likes_#{post.id}" class="likes">
	<%= display_likes post %>
</div>

app/views/posts/_post.html.erb
<div class="post-page">
	<div class="row">

	 	<div class="form-group">
	 		<div class="one_post">
	 			<div class="bloc-post-head">
	 				<div class="user row">
	 				<div class="userphoto col-sm-4">
	 					<%= profile_avatar_select(post.user) %>
	 				</div>
	 				<div class="username col-sm-8">
		 				<%= link_to post.user.user_name, profile_path(post.user.user_name) %>
	 				</div>
	 				
		 		</div>
		 		<div class="photo-post">
		 			<%= link_to (image_tag post.image.url(:medium), class:'img-responsive  center-block'), post_path(post) %>
		 		</div>
	 			</div>
		 		<div class="bloc-post">
			 		<div class="time">
			 			<%= time_ago_in_words post.created_at %>
			 		</div>
			 		<%= post.legende %>
			 		

			 		<%= render 'posts/likes', post: post %>
			 		<hr>
			 		<div class="comments-block">
			 			<h4>Commentaires du post</h4>
				 		<div class="comments" id= "comments_<%= post.id %>">
					 		<% if post.comments %>
					 				<div class="comment">
					 					<%= render post.comments, post: post %>
					 				</div>
					 		<% end %>	
				 		</div>	
			 		</div>	
			 		<hr>
			 		<div class="row">
				 		<div class="like-form col-sm-2">
				 		<% if current_user.liked? post %>
				 			<%= link_to '', unlike_post_path(post.id), remote: true, id: "like_#{post.id}", class: " like glyphicon glyphicon-heart" %>
				 		<% else %>
							<%= link_to '', like_post_path(post.id), id: "like_#{post.id}", remote: true,class: " like glyphicon glyphicon-heart-empty" %>	
						<% end %>
				 		</div>
				 		<div class="form-comment col-sm-10">
				 			<%= form_for([post, post.comments.build], remote: true) do |f| %>
				 				<% f.text_field :content, placeholder: "Ajouter un commentaire...", class: "input-lg  comment_content", id: "comment_content_#{post.id}" %>
				 			<% end %>
				 		</div>	
			 		</div>
		 		</div>
	 		</div>
	 	</div>

 	</div>
</div>

app/views/posts/edit.html.erb
<%= simple_form_for @post do |f| %>
		<div class="row edit-post">
				<h2>Modifier le post</h2>
			<div class="form-group  col-lg-12">
				<%= f.input :image, label: 'Image', class: 'form-control' %>
			</div>
			<div class="form-group  col-lg-12">
				<%= f.text_field :legende, label: 'Légende', class: 'form-control description input-lg caption' %>
			</div>
			<div>
				<%= f.submit 'Enregistrer', class: 'btn btn-warning' %>
				<%= link_to 'Supprimer', post_path(), method: :delete, data: { confirm: "Etes-vous sûr de vouloir supprimer le post,?" }, class: 'btn btn-danger' %>
				<%= link_to 'Annuler', root_path, class: 'btn btn-default' %>
			</div>
		</div>
	
<% end %>

app/views/posts/index.html.erb
<h1> Pictugram </h1>
<div class="subtitle">Découvrez les passions des personnes à travers le monde</div>
<% @posts.each do |post| %>
	<%= render 'post', post: post %>
<% end %>

app/views/posts/like.js.erb
jQuery("#like_<%= @post.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');
jQuery("#like_<%= @post.id %>").attr('href', '/posts/<%= @post.id %>/unlike');
jQuery("#likes_<%= @post.id %>").html("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");

app/views/posts/new.html.erb
<div class="new-post">
	 <h1>Nouveau posts</h1>

 	<%= form_for @post do |f| %>

	 	<div class="row">

	 	<div class="form-group  col-lg-5">

	 		<%= f.label :image %><br>

	 		<%= f.file_field :image, class:'form-control' %>

	 		<%= f.label :legende %><br>

	 		<%= f.text_field :legende, class:'form-control' %>

	 	</div>

	 	</div>

	 	<div>
			<%= f.submit 'Ajouter', class: 'btn btn-primary' %>

	 	</div>

 	<% end %>
</div>	

app/views/posts/show.html.erb
<div class="buttons-edit-block-post">
	<% if @post.user.id == current_user.id %>
		<p class="button-post-edit"><%= link_to 'Retour en arrière', posts_path, class: 'btn btn-warning' %></p>
		<p class="button-post-edit"><%= link_to "Modifier le post", edit_post_path(), class: 'btn btn-info' %> </p>
	<% else %>
		<p class="button-post-edit"><%= link_to 'Retour en arrière', posts_path, class: 'btn btn-warning' %></p>
	<% end %>
</div>
<%= render 'post', post: @post %>

app/views/posts/unlike.js.erb
jQuery("#like_<%= @post.id %>").removeClass('glyphicon-heart').addClass('glyphicon-heart-empty');
jQuery("#like_<%= @post.id %>").attr('href', '/posts/<%= @post.id %>/like');
jQuery("#likes_<%= @post.id %>").html("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");

app/views/profiles/edit.html.erb
<div class="modif-profile">
	<%= form_for @user, url: {action: "update"}, html: { multipart: true } do |f| %>
		<h4>Image de profile:</h4>
		<%= profile_avatar_select(@user) %>
		<%= f.file_field :avatar, onChange:'(loadFile(event))' %>
		<h4>Modifier votre description</h4>
		<%= f.text_area :bio, label: false, rows: 4 %>
		<%= f.submit "Modifier profil", class: 'btn btn-success' %>
	<% end %>
</div>

app/views/profiles/show.html.erb
<div class="profile-block">
	
	<div class="row">
		<div class="profile-photo col-sm-4">
			<%= profile_avatar_select(@user) %>
		</div>
		<div class="col-sm-8">
			<h3 class="profile-username"><%= @user.user_name %></h3>
			<div><%= @user.bio %></div>
			<div><%= pluralize @user.posts.count, 'post' %></div>
			<% if @user == current_user %>
			<%= link_to 'Modifier votre profil', edit_profile_path(@user.user_name), class: 'btn edit-button' %>
		<% end %>
		</div>
	</div>

</div>	
<% @posts.each do |post| %>
	<%= render 'posts/post', post: post %>
<% end %>